source  "https://rubygems.org"

gem 'appium_lib', '~> 10.3', '>= 10.3.1'
gem 'rspec', '>= 3.8'
gem 'rubygems-bundler', '~> 1.4', '>= 1.4.5'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.1'
gem 'cucumber', '~> 3.1', '>= 3.1.2'